### ISSUE TITLE
Ekotrace streaming reports

### ISSUE THREAD

**Issue by arezou2** [auxoncorp/ekotrace#100]
~(internal document link removed)~

**Comment by ZackPierce** [comment]
# Why should we want to support streaming reports?
* Reduce the maximum size of report transmission buffers that end users must prepare
* Make the maximum size of transmission buffers fixed

# Challenges
* The amount of content per report that needs to be sent out per report is variable, dependent on what sort of activity the ekotrace instance has observed (events recorded, snapshots merged).
* The serialization format we're presently using, LCM, does not yet have complete streaming capabilities built for Rust.
  * rust-lcm-codec has many of the primitives for streaming reading and writing of fields, but not individual bytes
  * rust-lcm-codec lacks robust control flow and error-handling support for the "not all the data is here yet" / "the buffer is full, but it could get more space soon" types of cases
* The report contains an extension point field which (currently) allows for an arbitrary sized byte blob with opaque internal structure.
* Report streaming is likely to be mutually exclusive with regular agent operations (recording events, sending snapshots, etc). 
  * In order to prevent incoherent data transmission, we may have to lock out other agent operations while reports are being written out.  The alternative is a possibly-finicky data read/write interleaving scheme (plus additional internal storage space claimed just for this use)
  * Another unsavory alternative to locking is to reserve nearly double the agent's current storage needs to support holding a copy of the data reserved for report-streaming.
  * A more palatable option to avoid locking would be to treat internal log memory like a circular buffer and maintain wrapping cursors, only preventing regular agent activities when they would catch up with the report-outputting cursor range. 

# Proposal

How about we implement a fragmented/chunked reporting strategy with a fixed maximum chunk size for starters and save a fully byte-by-byte streaming option on the table for later.

A homogeneous fragment message layout could limit the statefulness anddifficulty of the protocol from a collector's perspective to the minimum of bookkeeping around waiting for a complete set of fragments to show up.

We already have a decent compact log format in service in memory based on interpreting a slice of u32s, so let's apply a  slight variant of that to our wire format. The bare minimum, beyond fragment-identification framing details, would be to pay attention to the endian-ness of the encoded values.

Though it will be an annoyance to have multiple serialization formats in play, I think that the first pass is to just switch to a compact-log style payload format for reports and introduce the chunked-reporting functions, leaving the conversion of snapshot wire representation to a separate effort.

**Comment by ZackPierce** [comment]
Further elaboration of what I plan on implementing here.

* Describe and implement a chunked reporting *wire* format based on our compact log format plus fragmentation-enabling framing.
  * Documentation and testing of the new wire format must meet or exceed extant documentation of the old LCM-based schema+format.
* A `ChunkedReporter` trait added and implemented for the public ekotrace object.  Methods akin to a fallible iterator.
  * `start_chunked_report(&mut self) -> Result<(), ReportError>` . Prepare for chunked reporting. Lock out ekotrace internal mutation.
  * `write_next_report_chunk(&mut self, destination_bytes: &mut [u8]) -> Result<usize, ReportError>` . Write up to 256 bytes of the chunked format into the 
  * `stop_chunked_report(&mut self) -> Result<bool, ReportError`
* Expose these methods in the C API with C idioms.
* Update the un-chunked report methods to use the same compact log payload.
* Stretch goal: introduce an optimized framing variant for the un-chunked reports.
* Update the reference collector to handle the new chunked format:
  * Switch handling style (chunked vs un-chunked) on the datagram's starting format-identifying fingerprint bytes
  * Manage rolling together chunks into a unified report
  * Configuration for deciding at what time/storage/completeness thresholds to stop holding on to incomplete reports.
* Test everything well.

**Comment by ZackPierce** [comment]
Implemented as of https://github.com/auxoncorp/ekotrace/pull/103
